function scenario = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.8 (R2020a) and Automated Driving Toolbox 3.1 (R2020a).
% Generated on: 10-Nov-2020 09:55:31

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    0 150 0];
road(scenario, roadCenters);

roadCenters = [-1.1 73.6 0;
    90.542 98.291 0];
road(scenario, roadCenters);

roadCenters = [0.1 0.2 0;
    100.2 0.2 0];
road(scenario, roadCenters);

roadCenters = [60 89.4 0;
    60.5 0.7 0];
road(scenario, roadCenters);

roadCenters = [90.515 98.298 0;
    0.4 149.7 0];
road(scenario, roadCenters);

roadCenters = [-0.1 0.4 0;
    0 150 0];
road(scenario, roadCenters);

roadCenters = [-0.3 0.1 0;
    0 150 0];
road(scenario, roadCenters);

roadCenters = [0 150 0;
    0 200 0];
road(scenario, roadCenters);

roadCenters = [-0.1 0.4 0;
    0 150 0];
road(scenario, roadCenters);

roadCenters = [59.1 34.9 0;
    -0.7 34.9 0];
road(scenario, roadCenters);

roadCenters = [77.8 180.2 0;
    80 250 0];
road(scenario, roadCenters);

roadCenters = [80 250 0;
    0 200 0];
road(scenario, roadCenters);

roadCenters = [104 210.1 0;
    107.2 250.5 0];
road(scenario, roadCenters);

roadCenters = [0 200 0;
    77.66 179.73 0];
road(scenario, roadCenters);

roadCenters = [140 252.9 0;
    143.67 -0.57 0];
road(scenario, roadCenters);

roadCenters = [143.7 -0.5 0;
    99.3 -0.1 0];
road(scenario, roadCenters);

roadCenters = [95 54.8 0;
    140.7 73.9 0];
road(scenario, roadCenters);

roadCenters = [78.4 225.6 0;
    139.1 186.5 0];
road(scenario, roadCenters);

roadCenters = [122.6 196.5 0;
    125.3 68.9 0];
road(scenario, roadCenters);

roadCenters = [104 210.1 0;
    107.2 250.5 0];
road(scenario, roadCenters);

roadCenters = [90.488 98.305 0;
    99.47 0.14 0];
road(scenario, roadCenters);

roadCenters = [80 250 0;
    140.4 253 0];
road(scenario, roadCenters);

roadCenters = [77.3 180.2 0;
    48.9 122.9 0];
road(scenario, roadCenters);

roadCenters = [77.66 179.98 0;
    98.1 172.4 0;
    107.3 153.7 0;
    106.4 133.6 0;
    90.535 98.338 0];
road(scenario, roadCenters);

