function [scenario, noeuds, graphe] = createRoads()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.8 (R2020a) and Automated Driving Toolbox 3.1 (R2020a).
% Generated on: 10-Nov-2020 16:00:12

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0.01 0.21 0;
    0.01 150.21 0];
road(scenario, roadCenters);

roadCenters = [0 73.6 0;
    90.542 98.291 0];
road(scenario, roadCenters);

roadCenters = [-3.01 0.26 0;
    100.22 0.03 0];
road(scenario, roadCenters);

roadCenters = [60 89.4 0;
    60.5 -0.4 0];
road(scenario, roadCenters);

roadCenters = [90.515 98.298 0;
    0.4 149.7 0];
road(scenario, roadCenters);

roadCenters = [146.3 -0.25 0;
    99.4 0.03 0];
road(scenario, roadCenters);

roadCenters = [77.8 180.2 0;
    80 250 0];
road(scenario, roadCenters);

roadCenters = [79.09 248.3 0;
    -0.91 198.3 0];
road(scenario, roadCenters);

roadCenters = [0.76 199.62 0;
    78.42 179.35 0];
road(scenario, roadCenters);

roadCenters = [139.82 251.16 0;
    143.34 -0.62 0];
road(scenario, roadCenters);

roadCenters = [146.3 -0.25 0;
    99.4 0.03 0];
road(scenario, roadCenters);

roadCenters = [94.32 54.48 0;
    142.38 74.54 0];
road(scenario, roadCenters);

roadCenters = [79 225.3 0;
    140.18 186.93 0];
road(scenario, roadCenters);

roadCenters = [122.9 197.9 0;
    125.4 68.2 0];
road(scenario, roadCenters);

roadCenters = [104 210.1 0;
    106.6 247.9 0];
road(scenario, roadCenters);

roadCenters = [90.488 98.305 0;
    99.47 0.14 0];
road(scenario, roadCenters);

roadCenters = [77.31 247.83 0;
    139.8 248.2 0];
road(scenario, roadCenters);

roadCenters = [77.3 180.2 0;
    48.9 122.9 0];
road(scenario, roadCenters);

roadCenters = [77.66 179.98 0;
    98.1 172.4 0;
    107.3 153.7 0;
    103.1 132.4 0;
    90.535 98.338 0];
road(scenario, roadCenters);

roadCenters = [3.88578e-16 148.26 0;
    0.6 200.76 0];
road(scenario, roadCenters);

roadCenters = [146.3 -0.25 0;
    99.4 0.03 0];
road(scenario, roadCenters);

roadCenters = [60 89.4 0;
    60.5 -0.4 0];
road(scenario, roadCenters);

roadCenters = [0 40 0;
    60 40 0];
road(scenario, roadCenters);

keys = 1:26;
values = {[0, 0, 0], [0, 40, 0], [0, 73.5, 0], [0.4, 149.7, 0], [0.76, 199.6, 0], [60.5, 0, 0], [60, 40, 0], [60, 89.4, 0], [48.9, 122.9, 0], [77.3, 180.2, 0], [78.7, 225, 0], [77.8, 247, 0], [99.5, 0.14, 0], [94.3, 54.48, 0], [90.53, 98.34, 0], [103.1, 132.4, 0], [107.3, 153.7, 0], [98.1, 172.4, 0], [104, 210.1, 0], [106.6, 247.9, 0], [125.4, 68.2, 0], [122.9, 197.9, 0], [143.34, -0.62, 0], [142.38, 74.54, 0], [140.8, 186.93, 0], [139.8, 248.2, 0]};
noeuds = containers.Map(keys, values);

s = [1,1,2,2,3,3,4,4,5,6,6,7,8,9,9,10,10,11,11,12,13,13,14,14,15,16,17,19,19,20,21,22,23,24,25];
t = [2,6,7,3,4,8,5,9,12,7,13,8,15,10,15,11,18,12,19,20,14,23,15,21,16,17,18,20,22,26,24,25,24,25,26];
weights = ones(1, length(s));
for i=1:length(weights)
    weights(i) = norm(noeuds(s(i))-noeuds(t(i)));
end
graphe = graph(s, t, weights);



